<div id="footer" class="wrapper">
	<div class="menu">
		<a title="关于我们" href="#/about/">关于我们</a>
		<a title="联系方式" href="#/contact/">联系方式</a>
		<a title="付款方式" href="#/payment/">付款方式</a>
		<a title="免责条款" href="#/disclaimer/">免责条款</a>
		<a title="站点地图" href="#/sitemap/">站点地图</a>
	</div>
	Copyright &copy; LazyCMS.net All Rights Reserved.<br/>
	{$lazycms}<br/>
	<a href="http://www.miibeian.gov.cn" target="_blank" title="信息产业部">京ICP备00000001号</a>
</div>