<div id="top">
	<div class="wrapper">
		<div class="logo"><a href="{$inst}"><img src="images/logo.png" alt="{$sitename}" /></a></div>
		<ul id="menu">
			<li><a class="active" href="{$inst}">首页</a></li>
			<li><a href="#/product/">产品</a></li>
			<li><a href="#/service/">服务</a></li>
			<li><a href="#/download/">下载</a></li>
			<li><a href="http://bbs.lazycms.com/" target="_blank">论坛</a></li>
		</ul>
	</div>
</div>