#!/bin/sh

cwd=$(cd "$(dirname "$0")"; pwd);

echo "Compressor Starting ...";

for file in `ls $cwd"/../../common/js/" | grep -v min.js`; do
    if [ $file = jquery.js ]; then continue; fi;
    target=${file%.*}.min.${file##*.};
    echo "Compress: $file to $target ...";
    java -jar "$cwd"/yuicompressor-2.4.2.jar --type js --charset utf-8 "$cwd"/../../common/js/"$file" -o "$cwd"/../../common/js/"$target";
done;

for path in `echo "common/editor/xheditor.js"; echo "admin/js/common.js"`; do
    file=${path##*/};
    target=${path%.*}.min.${file##*.};
    echo "Compress: $file to ${file%.*}.min.${file##*.} ...";
    java -jar "$cwd"/yuicompressor-2.4.2.jar --type js --charset utf-8 "$cwd"/../../"$path" -o "$cwd"/../../"$target";
done;


echo "Compressor End!";
